# Generated by Django 4.2 on 2024-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='email',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
